# Generated by Django 2.1.1 on 2018-11-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GemLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_hide', models.CharField(max_length=100)),
                ('item_class', models.CharField(default=None, max_length=100, null=True)),
                ('base_type', models.CharField(default=None, max_length=100, null=True)),
                ('socket_group', models.CharField(default=None, max_length=100, null=True)),
                ('identified', models.BooleanField(default=None, null=True)),
                ('corrupted', models.BooleanField(default=None, null=True)),
                ('elder_item', models.BooleanField(default=None, null=True)),
                ('shaper_item', models.BooleanField(default=None, null=True)),
                ('shaped_map', models.BooleanField(default=None, null=True)),
                ('font_size', models.PositiveSmallIntegerField(default=32)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection', models.CharField(max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='editor.ItemSection')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedSockets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('links', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MinimapIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayAlertSound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_id', models.PositiveSmallIntegerField()),
                ('volume', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayAlertSoundPositional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_id', models.PositiveSmallIntegerField()),
                ('volume', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('temp', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('quality', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('rarity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SetBackgroundColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField()),
                ('green', models.PositiveSmallIntegerField()),
                ('blue', models.PositiveSmallIntegerField()),
                ('alpha', models.PositiveSmallIntegerField(default=255)),
            ],
        ),
        migrations.CreateModel(
            name='SetBorderColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField()),
                ('green', models.PositiveSmallIntegerField()),
                ('blue', models.PositiveSmallIntegerField()),
                ('alpha', models.PositiveSmallIntegerField(default=255)),
            ],
        ),
        migrations.CreateModel(
            name='SetTextColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField()),
                ('green', models.PositiveSmallIntegerField()),
                ('blue', models.PositiveSmallIntegerField()),
                ('alpha', models.PositiveSmallIntegerField(default=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sockets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('sockets', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StackSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='background_color',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.SetBackgroundColor'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='beam',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.PlayEffect'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='border_color',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.SetBorderColor'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='drop_level',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.DropLevel'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='gem_level',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.GemLevel'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='height',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Height'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='icon',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.MinimapIcon'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='item_level',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.ItemLevel'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='map_tier',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.MapTier'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='quality',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Quality'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='rarity',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Rarity'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='section',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.ItemSection'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='sockets',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Sockets'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='sockets_linked',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.LinkedSockets'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='sound',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.PlayAlertSound'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='sound_pos',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.PlayAlertSoundPositional'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='stack_size',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.StackSize'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='subsection',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.ItemSubSection'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='text_color',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.SetTextColor'),
        ),
        migrations.AddField(
            model_name='itemsettings',
            name='width',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Width'),
        ),
    ]
