# Generated by Django 2.1.1 on 2018-11-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('showhide', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=100)),
                ('sound', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('beam', models.CharField(max_length=100)),
            ],
        ),
    ]
